CREATE TABLE IF NOT EXISTS users (
    id                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username               VARCHAR(100),
    password_hash          VARCHAR(255),
    full_name              VARCHAR(200)  NOT NULL,
    email                  VARCHAR(200)  NOT NULL,
    role                   ENUM('student', 'instructor', 'staff', 'admin')     NOT NULL,
    student_id             VARCHAR(20),
    google_sub             VARCHAR(100),
    gpa                    DECIMAL(3,2),
    faculty                VARCHAR(200),
    year                   SMALLINT,
    is_active              BOOLEAN       NOT NULL DEFAULT true,
    created_at             DATETIME(3),
    updated_at             DATETIME(3),

    transcript_grades      JSON,
    transcript_status      VARCHAR(50),
    transcript_message     TEXT,
    transcript_confidence  DECIMAL(5,4),
    transcript_updated_at  DATETIME(3),
    UNIQUE KEY idx_users_username (username),
    UNIQUE KEY idx_users_student_id (student_id),
    UNIQUE KEY idx_users_google_sub (google_sub),
    UNIQUE KEY idx_users_email_unique ((NULLIF(email, '')))
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
