// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/courses/import": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "แสดงชื่อผู้สอนตามที่พิมพ์มาในไฟล์เสมอ ระบบพยายามจับคู่ชื่อแรกกับผู้ใช้ role=instructor ที่มีอยู่จริงเพื่อผูกวิชากับบัญชีนั้น (ให้อาจารย์ล็อกอินดูวิชาของตัวเองได้) แต่ถ้าจับคู่ไม่ได้ก็ไม่มีผลต่อการนำเข้า รหัสวิชาซ้ำกันได้ (คนละกลุ่มเรียน) มีเพียงแถวที่ว่างจริงๆ เท่านั้นที่จะถูกข้าม",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "นำเข้ารายวิชาจากไฟล์ Excel (.xlsx)",
                "parameters": [
                    {
                        "type": "file",
                        "description": "ไฟล์ Excel รายวิชา .xlsx (คอลัมน์: รายวิชา, ชื่อรายวิชา, COURSENAME, หน่วยกิต, กลุ่ม, รับ, ลงทะเบียนแล้ว, เวลา, ผู้สอน)",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ภาคการศึกษา",
                        "name": "semester",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ปีการศึกษา",
                        "name": "academic_year",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admin.ImportCoursesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/courses/term": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "ใช้เพื่อล้างข้อมูลที่นำเข้าผิดพลาด เช่น หลังจากอัปโหลดไฟล์ Excel ผิดเทอม",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "ลบวิชาทั้งหมดของภาคการศึกษาที่ระบุ",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ภาคการศึกษา",
                        "name": "semester",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ปีการศึกษา",
                        "name": "academic_year",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admin.DeleteCoursesByTermResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/logs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "ดู activity log",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "กรองตาม user ID",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "GET",
                            "POST",
                            "PUT",
                            "DELETE"
                        ],
                        "type": "string",
                        "description": "กรองตาม HTTP method",
                        "name": "method",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "หน้า (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "จำนวนต่อหน้า (default 50)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.LogsResponse"
                        }
                    }
                }
            }
        },
        "/admin/stats": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "สถิติภาพรวมของระบบ",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admin.AdminStatsResponse"
                        }
                    }
                }
            }
        },
        "/admin/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "รายการผู้ใช้ทั้งหมด",
                "parameters": [
                    {
                        "enum": [
                            "student",
                            "instructor",
                            "staff",
                            "admin"
                        ],
                        "type": "string",
                        "description": "กรองตาม role",
                        "name": "role",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ค้นหาด้วยชื่อหรืออีเมล",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "จำนวนต่อหน้า (default 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "ออฟเซ็ต (default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.User"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "สร้างผู้ใช้ใหม่ (ชื่อ + บทบาทเท่านั้น)",
                "parameters": [
                    {
                        "description": "ข้อมูลผู้ใช้",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/users/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "แก้ไขชื่อ/บทบาทผู้ใช้",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "ข้อมูลที่ต้องการแก้ไข",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/users/{id}/courses": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "จับคู่ด้วย ID บัญชีโดยตรง และด้วยชื่อกับข้อมูลผู้สอนที่นำเข้าจากไฟล์ Excel (ครอบคลุมทั้งผู้สอนหลักและผู้ร่วมสอน)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "รายวิชาที่อาจารย์คนนี้สอน",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Course"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/users/{id}/status": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "อัพเดตสถานะผู้ใช้ (เปิด/ปิด)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "สถานะใหม่",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.UpdateUserStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/google": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "เข้าสู่ระบบด้วย Google",
                "parameters": [
                    {
                        "description": "Google credential",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.GoogleLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.GoogleLoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "เข้าสู่ระบบ",
                "parameters": [
                    {
                        "description": "ข้อมูลล็อกอิน",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "ออกจากระบบ",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.MessageResponse"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "ดูข้อมูลผู้ใช้ปัจจุบัน",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.MeResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/courses": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "courses"
                ],
                "summary": "รายการวิชาทั้งหมด (สาธารณะ)",
                "parameters": [
                    {
                        "enum": [
                            "open",
                            "closing_soon",
                            "closed",
                            "draft",
                            "archived"
                        ],
                        "type": "string",
                        "description": "กรองตามสถานะ",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ค้นหาด้วยชื่อหรือรหัสวิชา",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Course"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/courses/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "courses"
                ],
                "summary": "ดูรายละเอียดวิชา (สาธารณะ)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Course ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Course"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/instructor/applications/bulk-review": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "instructor"
                ],
                "summary": "ตรวจสอบใบสมัครแบบกลุ่ม",
                "parameters": [
                    {
                        "description": "รายการใบสมัครและผลการตรวจสอบ",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/teacher.BulkReviewRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.BulkReviewResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/instructor/applications/{id}/review": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "instructor"
                ],
                "summary": "ตรวจสอบใบสมัคร (อาจารย์/สตาฟ/แอดมิน)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Application ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "ผลการตรวจสอบ",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/teacher.ReviewRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Application"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/instructor/course-catalog": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "จับคู่ด้วยชื่ออาจารย์กับข้อมูลผู้สอนที่นำเข้าจากไฟล์ Excel เพื่อจำกัดตัวเลือกรหัสวิชาให้เหลือแค่วิชาที่ตัวเองสอนจริง",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "instructor"
                ],
                "summary": "รายวิชาที่อาจารย์คนนี้สอน (สำหรับ dropdown ตอนสร้างประกาศ)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Course"
                            }
                        }
                    }
                }
            }
        },
        "/instructor/courses": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "instructor"
                ],
                "summary": "รายการวิชาของอาจารย์",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Course"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "instructor"
                ],
                "summary": "สร้างวิชาใหม่",
                "parameters": [
                    {
                        "description": "ข้อมูลวิชา",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/teacher.CreateCourseRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Course"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/instructor/courses/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "instructor"
                ],
                "summary": "แก้ไขข้อมูลวิชา",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Course ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "ข้อมูลที่ต้องการแก้ไข",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/teacher.UpdateCourseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Course"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "instructor"
                ],
                "summary": "ลบวิชา",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Course ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/instructor/courses/{id}/applicants": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "instructor"
                ],
                "summary": "รายชื่อผู้สมัครของวิชา",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Course ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "ta",
                            "labboy"
                        ],
                        "type": "string",
                        "description": "กรองตามประเภทที่สมัคร",
                        "name": "role_applied",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "pending",
                            "accepted",
                            "rejected",
                            "withdrawn"
                        ],
                        "type": "string",
                        "description": "กรองตามสถานะ",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ค้นหาด้วยชื่อหรือรหัสนักศึกษา",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Application"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/instructor/courses/{id}/notify": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "instructor"
                ],
                "summary": "ส่งแจ้งเตือนนักศึกษาที่ผ่านการคัดเลือก",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Course ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/instructor/courses/{id}/status": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "instructor"
                ],
                "summary": "อัพเดตสถานะวิชา",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Course ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "สถานะใหม่",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/teacher.UpdateCourseStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Course"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/instructor/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "instructor"
                ],
                "summary": "ข้อมูลโปรไฟล์ของอาจารย์ (ตัวเอง)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "บันทึกลง database ทันที การเปลี่ยนแปลงจะแสดงในหน้าจัดการผู้ใช้ของแอดมินด้วย เพราะดึงจากข้อมูลผู้ใช้ชุดเดียวกัน",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "instructor"
                ],
                "summary": "แก้ไขโปรไฟล์ของอาจารย์ (ตัวเอง)",
                "parameters": [
                    {
                        "description": "ข้อมูลโปรไฟล์ที่ต้องการแก้ไข",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/teacher.UpdateInstructorProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                }
            }
        },
        "/student/applications": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "student"
                ],
                "summary": "รายการใบสมัครของนักศึกษา",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Application"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "student"
                ],
                "summary": "สมัครเป็น TA หรือ Lab Boy",
                "parameters": [
                    {
                        "description": "ข้อมูลการสมัคร",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.ApplyRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Application"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/student/applications/{id}/withdraw": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "student"
                ],
                "summary": "ถอนใบสมัคร",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Application ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Application"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/student/dashboard": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "student"
                ],
                "summary": "หน้าหลักนักศึกษา",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.StudentDashboardResponse"
                        }
                    }
                }
            }
        },
        "/student/notifications": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "student"
                ],
                "summary": "รายการแจ้งเตือนของนักศึกษา",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Notification"
                            }
                        }
                    }
                }
            }
        },
        "/student/notifications/read-all": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "student"
                ],
                "summary": "ทำเครื่องหมายแจ้งเตือนทั้งหมดว่าอ่านแล้ว",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                }
            }
        },
        "/student/notifications/{id}/read": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "student"
                ],
                "summary": "ทำเครื่องหมายแจ้งเตือนว่าอ่านแล้ว",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Notification ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                }
            }
        },
        "/student/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "student"
                ],
                "summary": "ดูโปรไฟล์นักศึกษา",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "student"
                ],
                "summary": "แก้ไขโปรไฟล์นักศึกษา",
                "parameters": [
                    {
                        "description": "ข้อมูลโปรไฟล์ที่ต้องการแก้ไข",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UpdateProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "admin.AdminStatsResponse": {
            "type": "object",
            "properties": {
                "accepted_applications": {
                    "type": "integer",
                    "example": 50
                },
                "open_courses": {
                    "type": "integer",
                    "example": 5
                },
                "pending_applications": {
                    "type": "integer",
                    "example": 30
                },
                "total_applications": {
                    "type": "integer",
                    "example": 200
                },
                "total_courses": {
                    "type": "integer",
                    "example": 15
                },
                "total_instructors": {
                    "type": "integer",
                    "example": 10
                },
                "total_students": {
                    "type": "integer",
                    "example": 80
                },
                "total_users": {
                    "type": "integer",
                    "example": 100
                }
            }
        },
        "admin.CreateUserRequest": {
            "type": "object",
            "required": [
                "full_name",
                "role"
            ],
            "properties": {
                "full_name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "role": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.UserRole"
                        }
                    ],
                    "example": "instructor"
                }
            }
        },
        "admin.DeleteCoursesByTermResponse": {
            "type": "object",
            "properties": {
                "deleted": {
                    "type": "integer",
                    "example": 12
                }
            }
        },
        "admin.ImportCourseResult": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "CS101"
                },
                "instructor": {
                    "type": "string",
                    "example": "John Doe; Jane Doe"
                },
                "row": {
                    "type": "integer",
                    "example": 2
                },
                "title": {
                    "type": "string",
                    "example": "Introduction to Programming"
                }
            }
        },
        "admin.ImportCoursesResponse": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/admin.ImportCourseResult"
                    }
                },
                "skipped": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/admin.ImportSkippedRow"
                    }
                }
            }
        },
        "admin.ImportSkippedRow": {
            "type": "object",
            "properties": {
                "reason": {
                    "type": "string",
                    "example": "empty row"
                },
                "row": {
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "admin.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "full_name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "role": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.UserRole"
                        }
                    ],
                    "example": "instructor"
                }
            }
        },
        "admin.UpdateUserStatusRequest": {
            "type": "object",
            "properties": {
                "is_active": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "handlers.ApplyRequest": {
            "type": "object",
            "required": [
                "course_id",
                "role_applied"
            ],
            "properties": {
                "course_id": {
                    "type": "integer",
                    "example": 1
                },
                "motivation": {
                    "type": "string",
                    "example": "ต้องการช่วยสอนนักศึกษา"
                },
                "role_applied": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.RoleApplied"
                        }
                    ],
                    "example": "ta"
                }
            }
        },
        "handlers.BulkReviewResponse": {
            "type": "object",
            "properties": {
                "updated": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "handlers.DashboardStats": {
            "type": "object",
            "properties": {
                "applied": {
                    "type": "integer",
                    "example": 2
                },
                "open_courses": {
                    "type": "integer",
                    "example": 5
                }
            }
        },
        "handlers.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "error message"
                }
            }
        },
        "handlers.GoogleLoginRequest": {
            "type": "object",
            "required": [
                "credential"
            ],
            "properties": {
                "credential": {
                    "type": "string",
                    "example": "eyJhbGci..."
                }
            }
        },
        "handlers.GoogleLoginResponse": {
            "type": "object",
            "properties": {
                "is_new_user": {
                    "type": "boolean",
                    "example": false
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGci..."
                },
                "user": {
                    "$ref": "#/definitions/models.User"
                }
            }
        },
        "handlers.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "secret"
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "handlers.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "eyJhbGci..."
                },
                "user": {
                    "$ref": "#/definitions/models.User"
                }
            }
        },
        "handlers.LogsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ActivityLog"
                    }
                },
                "limit": {
                    "type": "integer",
                    "example": 50
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "total": {
                    "type": "integer",
                    "example": 100
                }
            }
        },
        "handlers.MeResponse": {
            "type": "object",
            "properties": {
                "user": {
                    "$ref": "#/definitions/models.User"
                }
            }
        },
        "handlers.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "ออกจากระบบแล้ว"
                }
            }
        },
        "handlers.StudentDashboardResponse": {
            "type": "object",
            "properties": {
                "recent_applications": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Application"
                    }
                },
                "recent_courses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Course"
                    }
                },
                "stats": {
                    "$ref": "#/definitions/handlers.DashboardStats"
                }
            }
        },
        "handlers.UpdateProfileRequest": {
            "type": "object",
            "properties": {
                "faculty": {
                    "type": "string",
                    "example": "วิทยาการคอมพิวเตอร์"
                },
                "full_name": {
                    "type": "string",
                    "example": "สมชาย ใจดี"
                },
                "year": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "models.ActivityLog": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "duration_ms": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "ip": {
                    "type": "string"
                },
                "method": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "status_code": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "models.AppStatus": {
            "type": "string",
            "enum": [
                "pending",
                "accepted",
                "rejected",
                "withdrawn"
            ],
            "x-enum-varnames": [
                "AppPending",
                "AppAccepted",
                "AppRejected",
                "AppWithdrawn"
            ]
        },
        "models.Application": {
            "type": "object",
            "properties": {
                "applied_at": {
                    "type": "string"
                },
                "course_code": {
                    "type": "string"
                },
                "course_id": {
                    "type": "integer"
                },
                "course_title": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "motivation": {
                    "type": "string"
                },
                "note": {
                    "type": "string"
                },
                "reviewed_at": {
                    "type": "string"
                },
                "reviewed_by_id": {
                    "type": "integer"
                },
                "reviewed_by_name": {
                    "type": "string"
                },
                "role_applied": {
                    "$ref": "#/definitions/models.RoleApplied"
                },
                "status": {
                    "$ref": "#/definitions/models.AppStatus"
                },
                "student_code": {
                    "type": "string"
                },
                "student_email": {
                    "type": "string"
                },
                "student_faculty": {
                    "type": "string"
                },
                "student_gpa": {
                    "type": "number"
                },
                "student_id": {
                    "type": "integer"
                },
                "student_name": {
                    "description": "Computed fields (not in DB)",
                    "type": "string"
                },
                "student_year": {
                    "type": "integer"
                }
            }
        },
        "models.Course": {
            "type": "object",
            "properties": {
                "academic_year": {
                    "type": "integer"
                },
                "applicant_count": {
                    "type": "integer"
                },
                "capacity": {
                    "type": "integer"
                },
                "code": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "credits": {
                    "type": "string"
                },
                "deadline": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "english_title": {
                    "type": "string"
                },
                "enrolled": {
                    "type": "integer"
                },
                "group_note": {
                    "type": "string"
                },
                "has_lab": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "instructor_id": {
                    "type": "integer"
                },
                "instructor_name": {
                    "type": "string"
                },
                "instructors_raw": {
                    "description": "InstructorsRaw is the verbatim text of the spreadsheet's instructor\ncell (kept for display as-is, e.g. co-teaching names the system has\nno matching account for) — separate from InstructorID, which only\never points to a real, matched user account.",
                    "type": "string"
                },
                "labboy_accepted": {
                    "type": "integer"
                },
                "labboy_slots": {
                    "type": "integer"
                },
                "requirements": {
                    "type": "string"
                },
                "schedule": {
                    "type": "string"
                },
                "section": {
                    "type": "integer"
                },
                "semester": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/models.CourseStatus"
                },
                "ta_accepted": {
                    "type": "integer"
                },
                "ta_slots": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.CourseStatus": {
            "type": "string",
            "enum": [
                "open",
                "closing_soon",
                "closed",
                "draft",
                "archived"
            ],
            "x-enum-varnames": [
                "StatusOpen",
                "StatusClosingSoon",
                "StatusClosed",
                "StatusDraft",
                "StatusArchived"
            ]
        },
        "models.Notification": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "course_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_read": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.RoleApplied": {
            "type": "string",
            "enum": [
                "ta",
                "labboy"
            ],
            "x-enum-varnames": [
                "RoleTA",
                "RoleLabBoy"
            ]
        },
        "models.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "description": "Email has no gorm uniqueIndex tag: admin-created accounts start with a\nblank email (filled in later via Google sign-in), so uniqueness is\nenforced instead by a partial index that ignores empty strings — see\ndatabase/connection.go.",
                    "type": "string"
                },
                "faculty": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "google_sub": {
                    "type": "string"
                },
                "gpa": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "role": {
                    "$ref": "#/definitions/models.UserRole"
                },
                "student_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "models.UserRole": {
            "type": "string",
            "enum": [
                "student",
                "instructor",
                "staff",
                "admin"
            ],
            "x-enum-varnames": [
                "RoleStudent",
                "RoleInstructor",
                "RoleStaff",
                "RoleAdmin"
            ]
        },
        "teacher.BulkReviewRequest": {
            "type": "object",
            "required": [
                "application_ids",
                "status"
            ],
            "properties": {
                "application_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "note": {
                    "type": "string"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.AppStatus"
                        }
                    ],
                    "example": "accepted"
                }
            }
        },
        "teacher.CreateCourseRequest": {
            "type": "object",
            "required": [
                "academic_year",
                "code",
                "semester",
                "title"
            ],
            "properties": {
                "academic_year": {
                    "type": "integer",
                    "example": 2567
                },
                "code": {
                    "type": "string",
                    "example": "CS101"
                },
                "deadline": {
                    "type": "string",
                    "example": "2026-08-01"
                },
                "description": {
                    "type": "string"
                },
                "labboy_slots": {
                    "type": "integer",
                    "example": 2
                },
                "requirements": {
                    "type": "string"
                },
                "semester": {
                    "type": "string",
                    "example": "1"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.CourseStatus"
                        }
                    ],
                    "example": "draft"
                },
                "ta_slots": {
                    "type": "integer",
                    "example": 3
                },
                "title": {
                    "type": "string",
                    "example": "Introduction to Programming"
                }
            }
        },
        "teacher.ReviewRequest": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "note": {
                    "type": "string",
                    "example": "ผ่านการคัดเลือก"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.AppStatus"
                        }
                    ],
                    "example": "accepted"
                }
            }
        },
        "teacher.UpdateCourseRequest": {
            "type": "object",
            "properties": {
                "academic_year": {
                    "type": "integer",
                    "example": 2567
                },
                "code": {
                    "type": "string",
                    "example": "CS101"
                },
                "deadline": {
                    "type": "string",
                    "example": "2026-08-01"
                },
                "description": {
                    "type": "string"
                },
                "labboy_slots": {
                    "type": "integer",
                    "example": 2
                },
                "requirements": {
                    "type": "string"
                },
                "semester": {
                    "type": "string",
                    "example": "1"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.CourseStatus"
                        }
                    ],
                    "example": "open"
                },
                "ta_slots": {
                    "type": "integer",
                    "example": 3
                },
                "title": {
                    "type": "string",
                    "example": "Introduction to Programming"
                }
            }
        },
        "teacher.UpdateCourseStatusRequest": {
            "type": "object",
            "properties": {
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.CourseStatus"
                        }
                    ],
                    "example": "open"
                }
            }
        },
        "teacher.UpdateInstructorProfileRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "somchai@su.ac.th"
                },
                "faculty": {
                    "type": "string",
                    "example": "ภาควิชาวิทยาการคอมพิวเตอร์"
                },
                "full_name": {
                    "type": "string",
                    "example": "ผู้ช่วยศาสตราจารย์ ดร.สมชาย ใจดี"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "LabAssist API",
	Description:      "API สำหรับระบบจัดการ TA ภาควิชา CS มหาวิทยาลัยศิลปากร",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
